### ISSUE TITLE
gradle build fails on MacBook (cannot find symbol)

### ISSUE THREAD

**Issue by jorgenhorstink** [VaughnVernon/IDDD_Samples#9]
Hi,

We are preparing for the IDDD_Workshop in Paris and are getting the following error when running `gradle build`. We are not so familiar with Java (understatement), so I have no clue if this has to do with our Java version, or some other settings.

I am working on a MacBook Air with Java 1.6.0_65. We used `brew install maven` and `brew install gradle` to install gradle on our machines, so I suppose we have the latest version. Anyone a clue?

`
.../IDDD_Samples/iddd_common/src/main/java/com/saasovation/common/port/adapter/messaging/slothmq/SlothWorker.java:152: cannot find symbol
symbol  : method bind(java.net.InetSocketAddress)
location: class java.nio.channels.ServerSocketChannel
                this.socket.bind(new InetSocketAddress(discoveryPort));
                           ^
.../IDDD_Samples/iddd_common/src/main/java/com/saasovation/common/port/adapter/messaging/slothmq/SlothWorker.java:191: cannot find symbol
symbol  : method bind(java.net.InetSocketAddress)
location: class java.nio.channels.ServerSocketChannel
            this.socket.bind(new InetSocketAddress(HUB_PORT));
                       ^
.../IDDD_Samples/iddd_common/src/main/java/com/saasovation/common/port/adapter/persistence/ResultSetObjectMapper.java:227: cannot find symbol
symbol  : method isAlphabetic(char)
location: class java.lang.Character
            if (Character.isAlphabetic(ch) && Character.isUpperCase(ch)) {
                         ^
3 errors
:iddd_common:compileJava FAILED
`
